on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - 2.7
          - 3.6
        dependency-set:
          - oldest
          - pinned
          - latest
          - extra
        test-set:
          - lib
          - static
          - examples
        exclude:
          - dependency-set: oldest
            test-set: static
          - dependency-set: oldest
            test-set: examples
          - dependency-set: latest
            test-set: static
          - dependency-set: latest
            test-set: examples
          - dependency-set: extra
            test-set: static
          - dependency-set: extra
            test-set: examples
        include:
          - python-version: 3.6
            dependency-set: mastereventlet
            test-set: lib
            experimental: true
          - python-version: 3.6
            dependency-set: branchcoverage  # urg
            test-set: lib
            experimental: true

    continue-on-error: ${{ matrix.experimental }}

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: start rabbitmq
      run: |
        docker run -d --rm -p 15672:15672 -p 5672:5672 -p 5671:5671 --name nameko-rabbitmq ghcr.io/nameko/nameko-rabbitmq:3.6.6
        docker cp nameko-rabbitmq:/srv/ssl certs

    - name: install toxiproxy
      run: |
        mkdir $PWD/bin
        wget -O $PWD/bin/toxiproxy-server https://github.com/Shopify/toxiproxy/releases/download/v2.0.0/toxiproxy-server-linux-amd64
        chmod +x $PWD/bin/toxiproxy-server
        sudo ln -s $PWD/bin/toxiproxy-server /usr/local/bin/toxiproxy-server


    - name: install libenchant
      run: |
        sudo apt-get install -y libenchant-dev

    - name: install test dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions

    - name: test with tox
      run: tox
      env:
        TOX_ENV: py${{ matrix.python-version }}-${{ matrix.dependency-set }}-${{ matrix.test-set }}

    - name: generate distributables
      run: |
        python setup.py sdist bdist_wheel
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')

    - name: publish to pypi
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')